config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
      post :add_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'home'

end

app/models/group.rb
class Group < ActiveRecord::Base

	belongs_to :owner, :class_name => 'User'
	belongs_to :parent, :class_name => 'Group'
	has_many :forms, -> { order name: :asc }, :dependent => :delete_all
	has_many :subgroups, -> { order name: :asc }, foreign_key: :parent_id, :class_name => 'Group', :dependent => :delete_all

  has_many :permissions, :dependent => :delete_all
	has_many :users, through: :permissions

  has_many :moderator_permissions, -> { where role_rank: 0 }, :class_name => 'Permission', :dependent => :delete_all
  has_many :moderators, source: :user, through: :moderator_permissions

  has_many :editor_permissions, -> { where role_rank: 1 }, :class_name => 'Permission', :dependent => :delete_all
  has_many :editors, source: :user, through: :editor_permissions

	before_create :set_supergroups

	def set_supergroups
		if parent
			group_index = parent.supergroups.max_by{ |k,v| v }.try(:last) || 0

			self.supergroups = parent.supergroups.merge({ "#{parent_id}" => group_index.to_i + 1 })
		else
			self.supergroups = {}
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, except: [:index, :show]

  # GET /groups
  def index
    @top_level_groups = Group.where(:parent_id => [false, nil])
  end

  def home
    if logged_in?
      # The user's personal group (user_group) is the only group with both their ID, and a null group_id
      @user_group = Group.where(:owner_id => session[:user_id], :parent_id => [false, nil]).first! # First ensures a single record
      redirect_to :action => 'show', :id => @user_group.id
    else
      # If a user is not logged in, the Group index will show all user's personal groups.
      @top_level_groups = Group.where(:parent_id => [false, nil])
      render :index
    end
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.parent_id = params[:parent_id]
    @group.owner = @group.parent.owner

    unless can_edit?
      redirect_to group_url(@group.parent), notice: "I'm sorry Dave, I can't let you do that."
    end
  end

  # GET /groups/1/edit
  def edit
    @user ||= current_user
    get_permission_variables

    unless can_edit?
      redirect_to group_url(@group), notice: "I'm sorry Dave, I can't let you do that."
    end
  end

  # POST /groups
  def create
    @group = Group.new(group_params)
    @group.parent_id = params[:parent_id]
    @group.owner = @group.parent.owner
    unless can_edit?
      redirect_to group_url(@group.parent), notice: "I'm sorry Dave, I can't let you do that."
    end
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    unless can_moderate?
      redirect_to group_url(@group), notice: "I'm sorry Dave, I can't let you do that."
    else
      get_permission_variables
      if @group.update(group_params)
        redirect_to edit_group_url(@group), notice: 'Group was successfully updated.'
      else
        redirect_to edit_group_url(@group), notice: 'Something went wrong!'
      end
    end
  end

  # DELETE /groups/1
  def destroy
    unless can_moderate? and !@group.parent.nil?
      redirect_to group_url(@group), notice: "I'm sorry Dave, I can't let you do that."
    else
      @redirect = @group.parent
      @group.destroy
      redirect_to group_url(@redirect), notice: 'Group was successfully deleted.'
    end
  end

  def remove_permission
    @group = Group.find(params[:id])

    unless can_moderate?
      redirect_to edit_group_url(@group), notice: "I'm sorry Dave, I can't let you do that."
    else
      @user = User.find(params[:remove_id])
      @permission = Permission.where(:user => @user, :group => @group)
      @permission.destroy_all
      get_permission_variables
      redirect_to edit_group_url(@group)
    end
  end

  def add_permission
    @group = Group.find(params[:id])

    unless can_moderate?
      redirect_to edit_group_url(@group), notice: "I'm sorry Dave, I can't let you do that."
    else
      if !params[:new_editor_id].blank?
        @group.permissions.create(:user_id => params[:new_editor_id], :group_id => @group.id, :role_rank => 1)
      end
      if !params[:new_moderator_id].blank?
        @group.permissions.create(:user_id => params[:new_moderator_id], :group_id => @group.id, :role_rank => 0)
      end
      get_permission_variables
      redirect_to edit_group_url(@group)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:owner_id, :parent_id, :name, :permissions)
    end

    def get_permission_variables
      @moderators = @group.moderators
      @editors = @group.editors
      @users = User.all
      @users = @users.reject{ |r| @moderators.include? r }
      @users = @users.reject{ |r| @editors.include? r }
      @options = @users.map{ |u| [u.username, u.id] }
    end
end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/views/groups/edit.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= link_to group_path(@group), class: "btn btn-sm btn-default" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
  <% end %>
  <div class="actions pull-right delete-button">

    <% unless @group.parent.nil? %>
      <% if can_delete? %>
        <%= link_to "Delete Group", @group, :method => "delete", :class => "btn btn-danger",
            data: { confirm: 'WARNING: This action cannot be reversed! Are you sure?' }
        %>
      <% end %>
    <% end %>
    <% if can_moderate? %>
      <%= f.submit class: 'btn btn-default' %>
    <% end %>
  </div>
  <div class="panel panel-default top7">
    <div class="panel-heading">
      <h1 class="panel-title">Group Name</h1>
    </div>
    <% if can_moderate? %>
      <div class="has-feedback edit-name">
        <%= f.text_field :name, class: 'form-control' %>
        <span class="glyphicon glyphicon-edit form-control-feedback"></span>
      </div>
    <% else %>
      <div class="has-feedback edit-name">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    <% end %>
  </div>
<% end %>
<div class="panel panel-default top7">
  <div class="panel-heading">
    <h1 class="panel-title">Moderators</h1>
  </div>
  <div class="panel-body list-group">
    <% @moderators.each do |moderator| %>
      <div class="list-group-item">
        <span class="lead">
          <%= moderator.username %>
        </span>
        <% if can_moderate? %>
          <span class="lead pull-right delete-button">
            <%= link_to 'Remove', remove_permission_group_path(:remove_id => moderator.id), class: "btn-sm btn-danger", method: :delete_permission, data: { confirm: 'Are you sure?' } %>
          </span>
        <% end %>
      </div>
    <% end %>
    <% if is_moderator? || is_super? %>
      <div class="list-group-item">
        <span class="lead">
          <%= form_tag(add_permission_group_path, method: "post") do %>
            <%= select_tag(:new_moderator_id, options_for_select(@options), :include_blank => true) %>
            <%= button_tag class: 'btn btn-sm btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              Add Moderator
            <% end %>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
</div>
<div class="panel panel-default top7">
  <div class="panel-heading">
    <h1 class="panel-title">Editors</h1>
  </div>
  <div class="panel-body list-group">
    <% @editors.each do |editor| %>
      <div class="list-group-item">
        <span class="lead">
          <%= editor.username %>
        </span>
        <% if can_moderate? %>
          <span class="lead pull-right delete-button">
            <%= link_to 'Remove', remove_permission_group_path(:remove_id => editor.id), class: "btn-sm btn-danger", method: :delete_permission, data: { confirm: 'Are you sure?' } %>
          </span>
        <% end %>
      </div>
    <% end %>
    <% if is_moderator? || is_super? %>
      <div class="list-group-item">
        <span class="lead">
          <%= form_tag(add_permission_group_path, method: "post") do %>
            <%= select_tag(:new_editor_id, options_for_select(@options), :include_blank => true) %>
            <%= button_tag class: 'btn btn-sm btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              Add Editor
            <% end %>
          <% end %>
        </span>

      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="panel panel-default top7">
  <div class="panel-heading">
    <h1 class="panel-title">Primary Groups</h1>
  </div>
  <div class="panel-body list-group">
    <% @top_level_groups.each do |group| %>
      <%= link_to group, class: "list-group-item" do %>
        <span class="lead">
          <span class="glyphicon glyphicon-folder-close"></span>
          <%= group.name %>
        </span>
      <% end %>
    <% end %>
  </div>
</div>

<p><strong>Warning: We are currently under active development, and cannot guarantee the privacy of data posted to this site.</strong><p>

<p><strong><a href='http://216.155.145.169/groups/2/forms/1/responses/new'>Click Here</a> for a full implementation of the BRCA1 Breast Cancer Screening survey.</strong></p>

app/views/groups/new.html.erb
<%= link_to group_path(@group.parent), class: "btn btn-sm btn-default" do %>
  <span class="glyphicon glyphicon-chevron-left"></span>
  Back
<% end %>
<h2>New Group</h2>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag(:parent_id, @group.parent_id) %>
  <div class="field">
    <%= f.label "Group Name:" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/groups/show.html.erb
<% if @group.parent %>
  <%= link_to group_path(@group.parent), class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
  <% end %>
<% elsif not logged_in? %>
  <%= link_to groups_path, class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
  <% end %>
<% end %>

<% if can_edit? %>
  <%= link_to new_group_path(:parent_id => @group.id), class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Add Subgroup
  <% end %>
  <%= link_to new_group_form_path(@group.id), class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Add Form
  <% end %>

  <%= link_to edit_group_path(@group), class: 'btn btn-sm btn-default pull-right' do %>
    <span class="glyphicon glyphicon-cog"></span>
    Settings
  <% end %>
<% end %>

<div class="panel panel-default top7">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @group.name %></h1>
  </div>
  <div class="panel-body list-group">
    <% @group.subgroups.each do |group| %>
      <%= link_to group, class: "list-group-item" do %>
        <span class="lead">
          <span class="glyphicon glyphicon-folder-close"></span>
          <%= group.name %>
        </span>
      <% end %>
    <% end %>
    <% @group.forms.each do |form| %>
      <%= link_to group_form_path(@group, form), class: "list-group-item" do %>
        <span class="lead">
          <span class="glyphicon glyphicon-list-alt"></span>
          <%= form.name %>
        </span>
      <% end %>
    <% end %>
  </div>
</div>