config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
      post :add_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'home'

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  include HandlebarsSupport

  before_action :set_parents
  before_action :set_response, only: [:show, :edit, :update, :destroy]


  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    @form = @response.form
    @group = @form.group
  end

  # GET /responses/new
  def new
    begin
      @compiled = compile_template(@form.template)
      @response = Response.new

      render layout: 'response'
    rescue V8::Error
       redirect_to group_form_path(@form.group, @form), notice: 'Your template syntax has a problem!'
    end
  end

  # GET /responses/1/edit
  def edit
    unless can_edit?
      redirect_to group_form_url(@response.form.group, @response.form), notice: "I'm sorry Dave, I can't let you do that."
    end
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new
    @response.form = @form
    @response.respondent = current_user
    @response.answers = params[:ans].merge(params[:ans]) { |k,v| v.is_a?(Array) ? v.join(',') : v }

    respond_to do |format|
      if @response.save
        format.html { redirect_to group_form_response_path(@group, @form, @response), notice: 'Response was successfully submitted.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    unless can_edit?
      redirect_to group_url(@form.group), notice: "I'm sorry Dave, I can't let you do that."
    end
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy

    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parents
      @group = Group.find params[:group_id]
      @form  = Form.find params[:form_id]
    end

    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:user_id, :answers, :form_id)
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/new.html.erb
<div ng-controller="formbuilder" >
  <h1 class="text-center"><%= @form.name %></h1>

  <%= form_for [@group, @form, @response], :html => {:novalidate => 'novalidate', :class => 'theform'} do %>
    <%= @compiled %>
    <div class="hide" ng-init="init()"></div>
  <% end %>
</div>

app/views/responses/show.html.erb
<%= link_to group_form_path(@group, @form), class: "btn btn-sm btn-default" do %>
  <span class="glyphicon glyphicon-chevron-left"></span>
  Back
<% end %>

<h3>Form: <span class="lead"><%= @form.name %></span></h3>

<h3>
  User:
  <span class="lead">
    <% if @response.respondent.nil? %>
      Anonymous Response
    <% else %>
      <%= @response.respondent.username %>
    <% end %>
  </span>
</h3>

<h3>Answers:</h3>
<table class="table">
  <thead>
    <th>Question</th>
    <th>Answer</th>
  </thead>
  <% @response.answers.each do |k, v| %>
    <tr>
      <td><%= k %></td>
      <td><%= v %></td>
    </tr>
  <% end %>
</table>