config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
      post :add_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'home'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_login, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:username], params[:password])
      @user_group = Group.where(:owner => @user, :parent_id => [false, nil]).first!
      redirect_to(@user_group, notice: 'Login Successful')
    else
      flash.now[:alert] = 'Login Failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:login, notice: 'Logged Out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
	<div class="field">
		<%= label_tag :username %><br />
		<%= text_field_tag :username %>
	</div>
	<div class="field">
		<%= label_tag :password %><br />
		<%= password_field_tag :password %>
	</div>
  <div class="actions">
    <%= button_tag 'Login', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<%= render 'form' %>